-- Mision MUCH - esquema Supabase
-- Copiar y ejecutar en Supabase SQL Editor.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.usuarios (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre TEXT,
  correo TEXT UNIQUE,
  avatar_url TEXT,
  fecha_registro TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.crear_usuario_desde_auth()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.usuarios (id, nombre, correo, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name'),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'avatar_url', NEW.raw_user_meta_data->>'picture')
  )
  ON CONFLICT (id) DO UPDATE SET
    nombre = EXCLUDED.nombre,
    correo = EXCLUDED.correo,
    avatar_url = EXCLUDED.avatar_url;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.crear_usuario_desde_auth();

CREATE TABLE IF NOT EXISTS public.estaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT UNIQUE,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  orden INT NOT NULL,
  estado TEXT DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA', 'INACTIVA')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.preguntas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estacion_id BIGINT NOT NULL REFERENCES public.estaciones(id) ON DELETE CASCADE,
  texto_pregunta TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.respuestas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pregunta_id BIGINT NOT NULL REFERENCES public.preguntas(id) ON DELETE CASCADE,
  texto_respuesta TEXT NOT NULL,
  es_correcta BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.progreso_usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  estacion_id BIGINT NOT NULL REFERENCES public.estaciones(id) ON DELETE CASCADE,
  completada BOOLEAN NOT NULL DEFAULT FALSE,
  completada_en TIMESTAMPTZ DEFAULT NOW(),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (user_id, estacion_id)
);

CREATE TABLE IF NOT EXISTS public.intentos_estacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  estacion_id BIGINT NOT NULL REFERENCES public.estaciones(id) ON DELETE CASCADE,
  aciertos INT DEFAULT 0,
  errores INT DEFAULT 0,
  puntaje INT DEFAULT 0,
  aprobado BOOLEAN DEFAULT FALSE,
  fecha_intento TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.imagenes_rompecabezas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estacion_id BIGINT REFERENCES public.estaciones(id) ON DELETE SET NULL,
  url_imagen TEXT NOT NULL,
  descripcion TEXT,
  orden INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.partidas_minijuego (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  puntaje INT NOT NULL DEFAULT 0,
  aprobado BOOLEAN DEFAULT FALSE,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  fecha_partida TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.boletos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  folio TEXT UNIQUE NOT NULL,
  estado TEXT DEFAULT 'NO_USADO' CHECK (estado IN ('USADO', 'NO_USADO')),
  fecha_generacion TIMESTAMPTZ DEFAULT NOW(),
  fecha_uso TIMESTAMPTZ
);

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preguntas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.respuestas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.progreso_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intentos_estacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.imagenes_rompecabezas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partidas_minijuego ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boletos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "usuarios_select_own" ON public.usuarios;
CREATE POLICY "usuarios_select_own"
ON public.usuarios FOR SELECT
TO authenticated
USING (auth.uid() = id);

DROP POLICY IF EXISTS "usuarios_insert_own" ON public.usuarios;
CREATE POLICY "usuarios_insert_own"
ON public.usuarios FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "usuarios_update_own" ON public.usuarios;
CREATE POLICY "usuarios_update_own"
ON public.usuarios FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "estaciones_read_authenticated" ON public.estaciones;
CREATE POLICY "estaciones_read_authenticated"
ON public.estaciones FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS "preguntas_read_authenticated" ON public.preguntas;
CREATE POLICY "preguntas_read_authenticated"
ON public.preguntas FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS "respuestas_read_authenticated" ON public.respuestas;
CREATE POLICY "respuestas_read_authenticated"
ON public.respuestas FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS "imagenes_read_authenticated" ON public.imagenes_rompecabezas;
CREATE POLICY "imagenes_read_authenticated"
ON public.imagenes_rompecabezas FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS "progreso_select_own" ON public.progreso_usuario;
CREATE POLICY "progreso_select_own"
ON public.progreso_usuario FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "progreso_insert_own" ON public.progreso_usuario;
CREATE POLICY "progreso_insert_own"
ON public.progreso_usuario FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "progreso_update_own" ON public.progreso_usuario;
CREATE POLICY "progreso_update_own"
ON public.progreso_usuario FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "intentos_select_own" ON public.intentos_estacion;
CREATE POLICY "intentos_select_own"
ON public.intentos_estacion FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "intentos_insert_own" ON public.intentos_estacion;
CREATE POLICY "intentos_insert_own"
ON public.intentos_estacion FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "intentos_update_own" ON public.intentos_estacion;
CREATE POLICY "intentos_update_own"
ON public.intentos_estacion FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "partidas_select_own" ON public.partidas_minijuego;
CREATE POLICY "partidas_select_own"
ON public.partidas_minijuego FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "partidas_insert_own" ON public.partidas_minijuego;
CREATE POLICY "partidas_insert_own"
ON public.partidas_minijuego FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "partidas_update_own" ON public.partidas_minijuego;
CREATE POLICY "partidas_update_own"
ON public.partidas_minijuego FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "boletos_select_own" ON public.boletos;
CREATE POLICY "boletos_select_own"
ON public.boletos FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "boletos_insert_own" ON public.boletos;
CREATE POLICY "boletos_insert_own"
ON public.boletos FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "boletos_update_own" ON public.boletos;
CREATE POLICY "boletos_update_own"
ON public.boletos FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
