window.MUCH_PREGUNTAS_BIODIVERSIDAD = [
  {"text":"📅 ¿Dónde surgió el Homo sapiens?","options":["China","África","Rusia","España"],"correctIndex":1,"points":10},
  {"text":"⌛ ¿Hace cuántos años apareció el Homo sapiens en África?","options":["500 mil","Entre 350 mil y 200 mil","100 mil","50 mil"],"correctIndex":1,"points":10},
  {"text":"🌍 ¿Qué evento climático impulsó la migración humana fuera de África?","options":["Sequía","Tormentas","Glaciación","Erupción volcánica"],"correctIndex":0,"points":10},
  {"text":"🧬 ¿Qué evidencias usan los científicos para reconstruir rutas migratorias?","options":["Fósiles, ADN y vestigios","Libros","Pirámides","Mitos"],"correctIndex":0,"points":10},
  {"text":"🗺️ ¿Cuál fue la ruta de salida de África hacia América?","options":["Atlántico","Bering","Pacífico","Mediterráneo"],"correctIndex":1,"points":10},
  {"text":"🦴 ¿En qué continente comenzó la migración humana?","options":["Asia","África","Europa","Oceanía"],"correctIndex":1,"points":10},
  {"text":"🇲🇦 ¿Dónde se halló evidencia de Homo sapiens de 350 mil años?","options":["Egipto","Marruecos","Kenia","Sudáfrica"],"correctIndex":1,"points":10},
  {"text":"🌽 ¿Qué importancia tuvo el maíz en Mesoamérica?","options":["Base de la dieta y economía","Solo ritual","Adorno","Moneda"],"correctIndex":0,"points":10},
  {"text":"🌱 ¿Qué son los teocintles?","options":["Progenitores silvestres del maíz","Plantas medicinales","Frijoles","Cactus"],"correctIndex":0,"points":10},
  {"text":"🇲🇽 ¿Cuántas razas de maíz existen en México?","options":["20","40","60","100"],"correctIndex":2,"points":10},
  {"text":"🍲 ¿Cuántos platillos existen con base en maíz en México?","options":["200","600+","50","100"],"correctIndex":1,"points":10},
  {"text":"👑 ¿Qué figura mítica se relaciona con el maíz?","options":["Centéotl","Tláloc","Huitzilopochtli","Quetzalcóatl"],"correctIndex":0,"points":10},
  {"text":"🌿 ¿Qué cultivos acompañan al maíz en la milpa?","options":["Trigo","Frijol y calabaza","Arroz","Papa"],"correctIndex":1,"points":10},
  {"text":"🚜 ¿Por qué la agricultura fue una revolución?","options":["Permitió civilizaciones estables","Generó guerras","Por comercio","Por religión"],"correctIndex":0,"points":10},
  {"text":"🔄 ¿Qué significa que los cultivos tengan plasticidad?","options":["Adaptarse a cambios ambientales","Duran poco","Son frágiles","Producen plástico"],"correctIndex":0,"points":10},
  {"text":"👨‍🌾 ¿Qué ecosistema agrícola de México es sostenible?","options":["La milpa","Plantaciones","Invernaderos","Pastizales"],"correctIndex":0,"points":10},
  {"text":"💧 ¿Qué son los servicios ambientales?","options":["Beneficios de la naturaleza","Servicios médicos","Productos de fábrica","Servicios públicos"],"correctIndex":0,"points":10},
  {"text":"🏙️ ¿Por qué son importantes los servicios ambientales en ciudades?","options":["Mantienen equilibrio y salud","Turismo","Decoración","Comercio"],"correctIndex":0,"points":10},
  {"text":"🌬️ Ejemplo de servicio ambiental:","options":["Oxígeno","Plástico","Dinero","Hierro"],"correctIndex":0,"points":10},
  {"text":"🔥 ¿Qué amenaza los servicios ambientales?","options":["Uso excesivo de recursos","Educación","Turismo","Deporte"],"correctIndex":0,"points":10},
  {"text":"🌳 ¿Qué ecosistemas garantizan servicios?","options":["Bosques y selvas","Calles","Fábricas","Carreteras"],"correctIndex":0,"points":10},
  {"text":"⛔ ¿Qué ocurre si se deterioran los ecosistemas?","options":["Se reducen beneficios","Hay más dinero","Nada","Mejora la vida"],"correctIndex":0,"points":10},
  {"text":"🦠 ¿Qué organismos participan en servicios ambientales?","options":["Animales, plantas, hongos","Solo humanos","Solo plantas","Robots"],"correctIndex":0,"points":10},
  {"text":"💎 ¿Por qué son invaluables los servicios ambientales?","options":["Son vitales para la vida","Se venden","Son moda","Se compran"],"correctIndex":0,"points":10},
  {"text":"🌄 ¿Por qué Chiapas es un estado biodiverso?","options":["Muchos ecosistemas y especies","Es pequeño","Es árido","Por minería"],"correctIndex":0,"points":10},
  {"text":"🏞️ Ecosistemas de Chiapas:","options":["Bosques, selvas, ríos","Desiertos","Tundra","Sabana"],"correctIndex":0,"points":10},
  {"text":"📊 ¿Cuántos estados destacan por biodiversidad junto con Chiapas?","options":["3","10","5","1"],"correctIndex":0,"points":10},
  {"text":"🔍 ¿Qué efecto tienen los descubrimientos de nuevas especies en Chiapas?","options":["Enriquecen listados biológicos","Nada","Reducen especies","Causan problemas"],"correctIndex":0,"points":10},
  {"text":"🎨 ¿Qué significa que Chiapas tenga vida de todos colores?","options":["Gran diversidad","Poca fauna","Solo aves","Un mito"],"correctIndex":0,"points":10},
  {"text":"🦅 ¿Qué ave rapaz gigante habita en Chiapas?","options":["Águila harpía","Águila real","Cóndor","Águila pescadora"],"correctIndex":0,"points":10},
  {"text":"🦧 ¿Qué mono habita en la Selva Lacandona?","options":["Mono araña","Mono ardilla","Mono titi","Mono capuchino"],"correctIndex":0,"points":10},
  {"text":"☕ ¿Qué producto de Chiapas es famoso mundialmente?","options":["Café","Té","Vino","Maíz"],"correctIndex":0,"points":10},
  {"text":"🎶 Instrumento musical típico de Chiapas:","options":["Marimba","Tambor","Guitarra","Violín"],"correctIndex":0,"points":10},
  {"text":"🎉 Fiesta tradicional de Chiapa de Corzo reconocida por UNESCO:","options":["Parachicos","Carnaval","Guelaguetza","Danza de los Viejitos"],"correctIndex":0,"points":10},
  {"text":"💧 ¿Qué cañón emblemático está en Chiapas?","options":["Cañón del Sumidero","Colorado","Cobre","Apurímac"],"correctIndex":0,"points":10},
  {"text":"🏛️ Gobernante maya enterrado en el Templo de las Inscripciones:","options":["Pakal el Grande","Moctezuma","Kukulkán","Itzamná"],"correctIndex":0,"points":10},
  {"text":"🏺 Zona arqueológica rival de Palenque:","options":["Toniná","Bonampak","Uxmal","Monte Albán"],"correctIndex":0,"points":10},
  {"text":"🦚 Ave considerada extinta y redescubierta en Chiapas:","options":["Guacamaya","Quetzal","Tucán","Loro"],"correctIndex":1,"points":10},
  {"text":"🐆 ¿Qué significa la palabra BALAM en maya?","options":["Jaguar","Puma","León","Tigre"],"correctIndex":0,"points":10},
  {"text":"⚡ Presa hidroeléctrica junto al Cañón del Sumidero:","options":["Chicoasén","La Angostura","Peñitas","Malpaso"],"correctIndex":0,"points":10},
  {"text":"🌊 Reserva natural costera de Chiapas con manglares:","options":["La Encrucijada","Sian Kaan","Calakmul","Vizcaíno"],"correctIndex":0,"points":10}
];
