window.MUCH_PREGUNTAS_ENERGIA = [
{"text":"Â¿QuÃ© elemento es bÃ¡sico para el desarrollo de un paÃ­s segÃºn el panel de bienvenida?","options":["La energÃ­a","El deporte","La educaciÃ³n","La agricultura"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© recursos son hoy esenciales para cualquier persona, segÃºn el texto?","options":["Gasolina y carbÃ³n","Electricidad y agua","PetrÃ³leo y leÃ±a","Oro y plata"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© medio utilizamos para realizar comunicaciones con el exterior, de acuerdo al panel?","options":["Correo postal","Internet","Radio antigua","SeÃ±ales de humo"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© dispositivos requieren energÃ­a elÃ©ctrica para funcionar, mencionados en la sala?","options":["AutomÃ³viles y bicicletas","Computadoras y telÃ©fonos celulares","Relojes de pulsera","Ventiladores manuales"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© organismos utilizan el consumo energÃ©tico per cÃ¡pita como indicador de desarrollo?","options":["Empresas privadas","Organismos internacionales","Escuelas locales","Gobiernos estatales"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© es el Sol segÃºn el panel del museo?","options":["Un planeta","Una estrella","Un satÃ©lite","Una roca gigante"],"correctIndex":1,"points":10},
{"text":"Â¿De quÃ© estÃ¡ compuesto el Sol?","options":["Hierro y oxÃ­geno","HidrÃ³geno y helio","Agua y nitrÃ³geno","Carbono y azufre"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de reacciones ocurren en el interior del Sol?","options":["Reacciones quÃ­micas de oxÃ­geno","Reacciones nucleares","Reacciones mecÃ¡nicas","Reacciones elÃ©ctricas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© porcentaje de la masa del Sistema Solar concentra el Sol?","options":["50%","99.85%","80%","25%"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© formas de energÃ­a percibimos del Sol en la Tierra?","options":["Gravitacional y nuclear","Luz y calor","ElÃ©ctrica y quÃ­mica","Sonora y mecÃ¡nica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© proceso permite a las plantas producir azÃºcares y oxÃ­geno?","options":["FotosÃ­ntesis","RespiraciÃ³n","DigestiÃ³n","FermentaciÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© gas toman las plantas del aire durante la fotosÃ­ntesis?","options":["DiÃ³xido de carbono","OxÃ­geno","HidrÃ³geno","Helio"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© orgÃ¡nulos celulares fabrican azÃºcares en las plantas?","options":["Cloroplastos","Mitocondrias","NÃºcleo","Ribosomas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© absorben las raÃ­ces del suelo para realizar fotosÃ­ntesis?","options":["Agua y minerales","Luz solar","Gas natural","OxÃ­geno"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© sucede con las plantas en la oscuridad?","options":["Se congelan","No pueden hacer fotosÃ­ntesis","Crecen mÃ¡s rÃ¡pido","Respiran mÃ¡s"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© debes hacer en el juego interactivo de la sala?","options":["Correr","Cachar objetos con la mano","Apagar una lÃ¡mpara","Saltar"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© se debe equilibrar segÃºn el juego?","options":["La energÃ­a solar","La energÃ­a que comes y la que gastas","La electricidad de la casa","La velocidad del viento"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© significa el Ã­cono de la bicicleta en la pantalla?","options":["Comer mÃ¡s","Realizar actividad fÃ­sica","Encender focos","Guardar energÃ­a"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© ocurre si no equilibras lo que comes y gastas?","options":["Tienes mÃ¡s energÃ­a limpia","Afecta tu salud","Comes menos","Gastas dinero"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© forma de energÃ­a actÃºa cuando algo se nos cae?","options":["ElÃ©ctrica","Gravedad","LumÃ­nica","MecÃ¡nica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de energÃ­a actÃºa cuando comemos para trabajar o estudiar?","options":["EnergÃ­a quÃ­mica","EnergÃ­a nuclear","EnergÃ­a mecÃ¡nica","EnergÃ­a solar"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© sucede cuando encendemos la luz en casa?","options":["Se genera energÃ­a hidrÃ¡ulica","Se combinan energÃ­a elÃ©ctrica y lumÃ­nica","Se produce energÃ­a nuclear","Se pierde calor"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© principio bÃ¡sico de la energÃ­a se menciona en este panel?","options":["No se transforma","No se crea ni se destruye","Se pierde siempre","Se apaga"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© aprendemos al caernos de pequeÃ±os?","options":["Que la gravedad nos atrae","Que la energÃ­a desaparece","Que el suelo se mueve","Que las caÃ­das no duelen"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© no hacen las mÃ¡quinas?","options":["Reducir el trabajo","Facilitar el esfuerzo","Ayudar con cargas pesadas","Multiplicar fuerza"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© modifican las mÃ¡quinas para ayudarnos?","options":["El tiempo","La fuerza aplicada y la distancia","El tamaÃ±o","La energÃ­a nuclear"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© mÃ¡quina simple aparece en la imagen de la grÃºa?","options":["Polea","Tornillo","Palanca","Rueda"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ocurre al usar un sistema de poleas?","options":["El objeto se hace mÃ¡s pesado","Se necesita menos esfuerzo","El objeto se destruye","No se mueve"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© ejemplos de trabajo se mencionan en el panel de las mÃ¡quinas simples?","options":["Moler granos y bombear agua","Pintar paredes y correr","Transportar aire y luz","Hacer fuego y viento"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© mÃ¡quina simple se menciona como primera usada?","options":["Palanca","Polea","Tornillo","Rueda"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ocurre si te alejas mÃ¡s del punto de apoyo en una palanca?","options":["Se necesita menos fuerza","Se rompe","No cambia nada","Se detiene"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© fuentes de energÃ­a eran dominantes antes de la industrializaciÃ³n?","options":["Fuego y fuerza muscular","EnergÃ­a nuclear","Gas natural","EnergÃ­a solar"],"correctIndex":0,"points":10},
{"text":"Â¿Por quÃ© las palancas ayudan en el trabajo?","options":["Multiplican la fuerza","Pesan menos","Consumen electricidad","Son modernas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ejemplo de palanca aparece en la imagen?","options":["Un sube y baja","Una rueda","Una grÃºa","Un molino"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© es un sistema segÃºn el panel?","options":["Conjunto de elementos que forman un todo","Un objeto aislado","Una cÃ©lula","Una piedra"],"correctIndex":0,"points":10},
{"text":"Â¿CuÃ¡l es el sistema mÃ¡s grande que conocemos?","options":["La Tierra","El Universo","El Sol","La VÃ­a LÃ¡ctea"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© mÃ¡quina imposible sueÃ±an algunos con crear?","options":["MÃ¡quina de vapor","MÃ¡quina de movimiento perpetuo","MÃ¡quina elÃ©ctrica","MÃ¡quina solar"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© enseÃ±a el experimento de las bolas metÃ¡licas (Newton)?","options":["ConservaciÃ³n y transformaciÃ³n de energÃ­a","El magnetismo","La gravedad desaparece","El sonido viaja"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© mÃ¡quina simple es el tornillo de ArquÃ­medes?","options":["Tornillo","Polea","Rueda","Palanca"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© funciÃ³n cumple este tornillo?","options":["Subir agua de un nivel a otro","Encender luces","Crear fuego","Transportar aire"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© mÃ¡quinas antiguas aprovechaban energÃ­a del aire y agua?","options":["Molino de viento y rueda hidrÃ¡ulica","Bicicleta y auto","AviÃ³n y barco","Polea y palanca"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© permitÃ­an hacer los molinos de viento segÃºn el panel?","options":["Moler granos","Crear electricidad","Volar","Hacer fuego"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© principio se demuestra con el tornillo en la sala?","options":["Bombear agua fÃ¡cilmente","Encender hornos","Crear energÃ­a nuclear","Aumentar temperatura"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© elemento mueve el tornillo de ArquÃ­medes?","options":["Arena","Agua","Aire","Minerales"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© acciÃ³n se pide en el panel del tornillo?","options":["Girar la manivela","Saltar","Correr","Empujar con la mano"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© recurso aprovecha la rueda hidrÃ¡ulica segÃºn el panel?","options":["Agua","Viento","Sol","Tierra"],"correctIndex":0,"points":10},
{"text":"Â¿Por quÃ© algunos inventos antiguos siguen vigentes hoy?","options":["Porque son fÃ¡ciles de usar","Porque son decorativos","Porque no gastan electricidad","Porque son modernos"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ejemplo de mÃ¡quina simple permite subir agua en la sala?","options":["Tornillo de ArquÃ­medes","Palanca","Rueda","Polea"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© recurso se usaba en China en el aÃ±o 100 a.n.e. para mover molinos de agua?","options":["CarbÃ³n","EnergÃ­a hidrÃ¡ulica","Gas natural","EnergÃ­a solar"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© aÃ±o en China se explotaba el gas natural transportado en tubos de bambÃº?","options":["900 d.n.e.","100 a.n.e.","1712","1769"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© describiÃ³ Al-Razi en el aÃ±o 900 d.n.e.?","options":["La fotosÃ­ntesis","El proceso de destilaciÃ³n para producir queroseno","La mÃ¡quina de vapor","El molino de viento"],"correctIndex":1,"points":10},
{"text":"Â¿QuiÃ©n construyÃ³ la primera mÃ¡quina de vapor en 1712?","options":["James Watt","Thomas Newcomen","Thomas Edison","Karl Benz"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© patentÃ³ James Watt en 1769?","options":["La turbina hidrÃ¡ulica","La primera mÃ¡quina de vapor comercial","El motor de gasolina","La turbina eÃ³lica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© recurso fue clave en 1750 para la RevoluciÃ³n Industrial?","options":["Gas natural","PetrÃ³leo","CarbÃ³n","EnergÃ­a solar"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© descubriÃ³ Edmond Becquerel en 1839?","options":["El motor elÃ©ctrico","El efecto fotovoltaico","La turbina eÃ³lica","La pila de Volta"],"correctIndex":1,"points":10},
{"text":"Â¿QuiÃ©n abriÃ³ la primera central elÃ©ctrica de carbÃ³n en 1882?","options":["Nikola Tesla","Thomas Edison","James Blyth","Alexander Graham Bell"],"correctIndex":1,"points":10},
{"text":"Â¿DÃ³nde se perforÃ³ el primer pozo petrolero comercial?","options":["Inglaterra","Estados Unidos","Rusia","Alemania"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© aÃ±o se construyÃ³ la primera central geotÃ©rmica del mundo?","options":["1911","1886","1950","1975"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© desarrollÃ³ Bell Labs en 1954?","options":["La primera turbina eÃ³lica","La primera celda solar de silicio","La lÃ¡mpara incandescente","La baterÃ­a de litio"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© dispositivo convierte energÃ­a hidrÃ¡ulica en energÃ­a mecÃ¡nica?","options":["Generador","Turbina hidrÃ¡ulica","Panel solar","Aerogenerador"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© estructura utilizan las centrales hidroelÃ©ctricas de embalse para almacenar agua?","options":["Presa","Molino","Turbina eÃ³lica","Palanca"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se busca mantener en un embalse?","options":["Un nivel constante de agua","La temperatura del agua","El caudal mÃ­nimo","La presiÃ³n del aire"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© producen las turbinas al girar con el agua?","options":["Luz","Gas","Electricidad","Calor"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© central hidroelÃ©ctrica del rÃ­o Grijalva tiene la cortina mÃ¡s alta de AmÃ©rica?","options":["La Angostura","ChicoasÃ©n","Malpaso","PeÃ±itas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© nombre reciben los dispositivos que transforman energÃ­a solar en calor?","options":["Turbinas solares","Colectores tÃ©rmicos","Paneles geotÃ©rmicos","Aerogeneradores"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© descubriÃ³ Edmond Becquerel en 1839?","options":["La energÃ­a nuclear","El efecto fotovoltaico","La palanca","La turbina de viento"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© puede hacer la energÃ­a solar tÃ©rmica en los hogares?","options":["Refrigerar alimentos","Perforar pozos","Generar petrÃ³leo","Producir carbÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© determina la temperatura de operaciÃ³n de los colectores solares?","options":["Color del agua","Material y forma","Lugar geogrÃ¡fico","Tipo de turbina"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© temperatura mÃ¡xima pueden alcanzar colectores solares de baja temperatura?","options":["50 Â°C","80 Â°C","Menor a 100 Â°C","200 Â°C"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© son los aerogeneradores?","options":["Dispositivos que convierten energÃ­a del viento en electricidad","Motores de combustiÃ³n","Paneles solares","Turbinas hidrÃ¡ulicas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© creÃ³ James Blyth en 1887?","options":["Primer aerogenerador","Motor de gasolina","Central geotÃ©rmica","BaterÃ­a solar"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© porcentaje de la electricidad mundial podrÃ­an producir los aerogeneradores en 2030?","options":["10%","20%","50%","80%"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© usaba la energÃ­a eÃ³lica en la antigÃ¼edad?","options":["Aviones","Molinos de viento","Paneles solares","Turbinas nucleares"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© relaciÃ³n existe entre el viento y el Sol?","options":["El viento se genera por la rotaciÃ³n terrestre y acciÃ³n solar","El Sol produce viento directamente","El viento crea energÃ­a solar","Ninguna"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se construyÃ³ en Rusia y EUA en 1950?","options":["Primer automÃ³vil","Primera planta nuclear","Primera turbina eÃ³lica","Primer colector solar"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© programa lanzÃ³ Brasil en 1975?","options":["EnergÃ­a nuclear","Programa PrÃ³-Ãlcool","EnergÃ­a eÃ³lica","HidroelÃ©ctricas"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© paÃ­s se construyÃ³ el primer parque eÃ³lico marino en 1991?","options":["Dinamarca","EUA","Inglaterra","Alemania"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© acuerdo internacional se firmÃ³ en 2015 sobre energÃ­a y clima?","options":["Acuerdo de Kioto","Acuerdo de ParÃ­s","Agenda 2030","Protocolo de Montreal"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© meta mundial se espera alcanzar para 2050?","options":["Eliminar el carbÃ³n","Cero emisiones netas","Prohibir petrÃ³leo","100% energÃ­a solar"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© construyeron Karl Benz y Gottlieb Daimler en 1886?","options":["Primer molino de viento","Primeros automÃ³viles de gasolina","Primer panel solar","Primera turbina hidrÃ¡ulica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© iniciÃ³ en 1935 en Reino Unido?","options":["Red nacional de transmisiÃ³n elÃ©ctrica","Central nuclear","Uso de la energÃ­a solar","Programa de biocombustibles"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se comenzÃ³ a usar en 1904 en Italia para generar electricidad?","options":["EnergÃ­a eÃ³lica","EnergÃ­a geotÃ©rmica","EnergÃ­a solar","Gas natural"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© aÃ±o se construyÃ³ la primera planta de energÃ­a nuclear en el mundo?","options":["1839","1950","1882","1975"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© aÃ±o se descubriÃ³ el petrÃ³leo en pozos comerciales en Estados Unidos?","options":["1858-1859","1900","1950","1887"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© recurso natural aprovechan las centrales hidroelÃ©ctricas?","options":["Viento","Agua","CarbÃ³n","Gas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© funciÃ³n cumplen las turbinas en una hidroelÃ©ctrica?","options":["Almacenar energÃ­a","Transformar energÃ­a hidrÃ¡ulica en mecÃ¡nica","Transportar agua","Generar calor"],"correctIndex":1,"points":10},
{"text":"Â¿DÃ³nde se encuentran cuatro de las hidroelÃ©ctricas mÃ¡s grandes de MÃ©xico?","options":["RÃ­o Grijalva","RÃ­o Amazonas","RÃ­o Nilo","RÃ­o Bravo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© impacto buscan minimizar los proyectos hidroelÃ©ctricos?","options":["El turismo","Impactos negativos en la naturaleza","La urbanizaciÃ³n","La minerÃ­a"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© central hidroelÃ©ctrica es la quinta mÃ¡s grande del mundo?","options":["Malpaso","ChicoasÃ©n","PeÃ±itas","ItaipÃº"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© nombre reciben los dispositivos que almacenan y transfieren calor solar?","options":["Colectores tÃ©rmicos","Aerogeneradores","Represas","Turbinas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© usos prÃ¡cticos tiene la energÃ­a solar tÃ©rmica?","options":["Calentar agua y cocinar","Perforar pozos petroleros","Generar gasolina","Extraer minerales"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de energÃ­a produce el efecto fotovoltaico?","options":["EnergÃ­a tÃ©rmica","EnergÃ­a elÃ©ctrica","EnergÃ­a mecÃ¡nica","EnergÃ­a quÃ­mica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© cientÃ­fico descubriÃ³ el efecto fotovoltaico?","options":["James Watt","Edmond Becquerel","Thomas Edison","Nikola Tesla"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© caracterÃ­stica tienen los colectores solares de alta temperatura?","options":["Superan los 100 Â°C","No almacenan calor","No dependen del material","Solo sirven en climas frÃ­os"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© recurso mueve los aerogeneradores?","options":["Agua","Viento","Gas","CarbÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© se utilizaba en la antigÃ¼edad para mover barcos y triturar granos?","options":["Aerogeneradores","Molinos de viento","Paneles solares","Turbinas hidrÃ¡ulicas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© paÃ­s construyÃ³ el primer parque eÃ³lico marino en 1991?","options":["Dinamarca","Alemania","Reino Unido","Brasil"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© acuerdo internacional se firmÃ³ en 2015 para reducir el cambio climÃ¡tico?","options":["Protocolo de Montreal","Acuerdo de ParÃ­s","Agenda 2050","Tratado de Kioto"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© aÃ±o estÃ¡ marcado como meta mundial para alcanzar cero emisiones netas?","options":["2030","2040","2050","2100"],"correctIndex":2,"points":10},
{"text":"Â¿CÃ³mo se llama la energÃ­a que recibimos directamente del Sol?","options":["RadiaciÃ³n solar","EnergÃ­a tÃ©rmica","EnergÃ­a quÃ­mica","Calor solar"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© efecto permite transformar la luz solar en electricidad?","options":["Efecto invernadero","Efecto fotovoltaico","Efecto gravitacional","Efecto calorÃ­fico"],"correctIndex":1,"points":10},
{"text":"Â¿Con quÃ© materiales se fabrican las celdas fotovoltaicas?","options":["PlÃ¡sticos","Semiconductores","Metales pesados","Madera"],"correctIndex":1,"points":10},
{"text":"Â¿Por quÃ© se conectan varias celdas fotovoltaicas?","options":["Para producir calor","Para generar suficiente electricidad","Para almacenar agua","Para concentrar luz"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© otro uso comÃºn tiene la radiaciÃ³n solar ademÃ¡s de electricidad?","options":["ProducciÃ³n de gas natural","Calentadores solares","Centrales nucleares","Motores de vapor"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© genera el movimiento de las olas del mar?","options":["EnergÃ­a tÃ©rmica","EnergÃ­a mareomotriz","EnergÃ­a geotÃ©rmica","EnergÃ­a quÃ­mica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© provoca la marea en la Tierra?","options":["Los volcanes","La fuerza gravitacional del Sol y la Luna","Los vientos","El movimiento de placas tectÃ³nicas"],"correctIndex":1,"points":10},
{"text":"Â¿DÃ³nde en MÃ©xico hay un alto potencial para aprovechar la energÃ­a de mareas?","options":["Lago de Chapala","Golfo de California","RÃ­o Bravo","Presa de Malpaso"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© altura pueden alcanzar algunas mareas?","options":["5 m","10 m","15 m","30 m"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© otro factor puede aprovecharse en el mar para generar energÃ­a?","options":["Diferencias de temperatura","Sedimentos marinos","Pesca","Corrientes de aire"],"correctIndex":0,"points":10},
{"text":"Â¿DÃ³nde ocurre naturalmente la fusiÃ³n nuclear?","options":["En volcanes","En estrellas como el Sol","En centrales hidroelÃ©ctricas","En reactores quÃ­micos"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© elementos se fusionan para liberar energÃ­a en el Sol?","options":["OxÃ­geno y carbono","HidrÃ³geno","Helio y nitrÃ³geno","Azufre"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© libera la fusiÃ³n nuclear?","options":["Agua","Grandes cantidades de energÃ­a","CarbÃ³n","OxÃ­geno"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© se necesita para que la fusiÃ³n nuclear sea viable en la Tierra?","options":["Que consuma mÃ¡s energÃ­a de la que produce","Que produzca mÃ¡s energÃ­a de la que consume","Que use carbÃ³n como combustible","Que se combine con fisiÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© reactor busca imitar la fusiÃ³n solar en la Tierra?","options":["Reactor Tokamak","Reactor de grafito","Reactor hidroelÃ©ctrico","Reactor de neutrones"],"correctIndex":0,"points":10},
{"text":"Â¿QuiÃ©n inventÃ³ la primera pila elÃ©ctrica en 1798?","options":["Luigi Galvani","Alessandro Volta","Thomas Edison","Edmond Becquerel"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© descubriÃ³ Luigi Galvani en 1780?","options":["Corriente alterna","ContracciÃ³n muscular con electricidad","Fotovoltaico","CombustiÃ³n interna"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© aÃ±o se creÃ³ la pila Daniell?","options":["1836","1798","1859","1866"],"correctIndex":0,"points":10},
{"text":"Â¿CuÃ¡l fue la primera baterÃ­a recargable inventada en 1859?","options":["Pila de hidrÃ³geno","BaterÃ­a plomo-Ã¡cido","Pila de zinc-carbÃ³n","Pila alcalina"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© aportÃ³ Georges LeclanchÃ© en 1866?","options":["Motor elÃ©ctrico","Pila LeclanchÃ©","BaterÃ­a de litio","Panel solar"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© pila se popularizÃ³ en 1867?","options":["Zinc-carbÃ³n","Aluminio","Plomo","NÃ­quel"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© baterÃ­a se creÃ³ en 1896?","options":["BaterÃ­a Columbia","BaterÃ­a de litio","BaterÃ­a de grafeno","Pila solar"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© baterÃ­a se desarrollÃ³ en 1899?","options":["NÃ­quel-cadmio","Zinc-carbÃ³n","Litio-iÃ³n","Plomo-Ã¡cido"],"correctIndex":0,"points":10},
{"text":"Â¿En quÃ© aÃ±o apareciÃ³ la pila de reloj?","options":["1956","1967","1985","1970"],"correctIndex":1,"points":10},
{"text":"Â¿QuiÃ©n desarrollÃ³ en 1985 el acumulador de litio?","options":["John B. Goodenough","Akira Yoshino","Edison","Becquerel"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© factor clave permite la implementaciÃ³n de energÃ­as renovables?","options":["ProducciÃ³n de carbÃ³n","Almacenamiento de energÃ­a","ExtracciÃ³n de petrÃ³leo","Uso de gas natural"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© aseguran las tecnologÃ­as de almacenamiento?","options":["Crecimiento econÃ³mico","Suministro constante y seguro","ProducciÃ³n de calor","ExpansiÃ³n urbana"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de baterÃ­a usan los telÃ©fonos celulares?","options":["Plomo-Ã¡cido","NÃ­quel","IÃ³n de litio","Zinc-carbÃ³n"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© ventaja tiene almacenar energÃ­a?","options":["Permite usarla solo de noche","Permite disponerla cuando hay poca o mucha","Permite usar solo carbÃ³n","Evita energÃ­as renovables"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© incrementa la confianza en las energÃ­as renovables?","options":["Combustibles fÃ³siles","TecnologÃ­as de almacenamiento","Plantas de carbÃ³n","Gasolina"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© aÃ±o se emitiÃ³ el Protocolo de Kioto?","options":["1997","1980","2015","2005"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© buscaba reducir el Protocolo de Kioto?","options":["ProducciÃ³n de agua","Emisiones de gases de efecto invernadero","PoblaciÃ³n mundial","Consumo de alimentos"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© consiste la transiciÃ³n energÃ©tica?","options":["Usar carbÃ³n como fuente principal","Usar energÃ­as renovables","Usar mÃ¡s petrÃ³leo","Aumentar gas natural"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© esquema mixto de energÃ­as se menciona en el Protocolo?","options":["Matriz energÃ©tica","Protocolo de Montreal","Agenda 2050","Red hidroelÃ©ctrica"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© fenÃ³menos estÃ¡n vinculados al consumo de combustibles fÃ³siles?","options":["ReforestaciÃ³n","Calentamiento global y cambio climÃ¡tico","Lluvias torrenciales","FormaciÃ³n de montaÃ±as"],"correctIndex":1,"points":10},
{"text":"Â¿CuÃ¡l es el reto actual de la energÃ­a?","options":["Abundancia de combustibles","Agotamiento de hidrocarburos","ReducciÃ³n del Sol","DisminuciÃ³n del agua"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© fuentes renovables destacan en MÃ©xico?","options":["Solar, eÃ³lica y geotÃ©rmica","CarbÃ³n, petrÃ³leo y gas","Uranio, carbÃ³n y biomasa","CarbÃ³n, gas y petrÃ³leo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© permiten las energÃ­as renovables?","options":["MÃ¡s contaminaciÃ³n","Seguridad energÃ©tica y sustentabilidad","Uso exclusivo de carbÃ³n","EliminaciÃ³n de tecnologÃ­a"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© recurso natural es biomasa?","options":["CarbÃ³n","Material orgÃ¡nico","Uranio","Gas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© recurso natural es energÃ­a renovable?","options":["CarbÃ³n","PetrÃ³leo","EÃ³lica","Gas"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© recurso es considerado energÃ­a no renovable?","options":["Solar","PetrÃ³leo","EÃ³lica","HidrÃ¡ulica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de energÃ­a incluye el petrÃ³leo, carbÃ³n y gas?","options":["Renovables","No renovables","Biomasa","Mareomotriz"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© problema causa la combustiÃ³n de energÃ­as no renovables?","options":["ReducciÃ³n de COâ‚‚","Efecto invernadero","ReforestaciÃ³n","EnergÃ­a solar"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© porcentaje de aumento anual de temperatura se estima hacia 2070?","options":["1%","5%","10%","20%"],"correctIndex":1,"points":10},
{"text":"Â¿CuÃ¡nto aumentarÃ­a la temperatura hacia 2070 segÃºn estimaciones?","options":["1 Â°C","2 Â°C","4 Â°C","6 Â°C"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© pÃ©rdida de alimentos podrÃ­a haber a finales de siglo?","options":["20%","50%","80%","100%"],"correctIndex":2,"points":10},
{"text":"Â¿De quÃ© depende la reducciÃ³n de emisiones de COâ‚‚?","options":["Uso de carbÃ³n","Acciones conjuntas de gobierno y ciencia","MÃ¡s gasolina","ProducciÃ³n de petrÃ³leo"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© se considera hoy el cambio climÃ¡tico acelerado?","options":["CÃ³digo rojo mundial","Oportunidad de negocio","FenÃ³meno local","Recurso renovable"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© paÃ­s tiene grandes retos frente a la energÃ­a no renovable?","options":["CanadÃ¡","MÃ©xico","Rusia","China"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© impacto tendrÃ¡ el cambio climÃ¡tico en el sector agrÃ­cola?","options":["ReducciÃ³n de lluvias","Desabasto de alimentos","Aumento de productividad","Crecimiento de granos"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© acciÃ³n urgente se necesita ante el cambio climÃ¡tico?","options":["Mayor uso de carbÃ³n","Responder con medidas inmediatas","Seguir con energÃ­as fÃ³siles","Detener energÃ­as renovables"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de baterÃ­a es la mÃ¡s usada en laptops y celulares actualmente?","options":["NÃ­quel-Cadmio","Plomo-Ã¡cido","Litio-ion","Zinc-carbÃ³n"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© problema ambiental generan las baterÃ­as al desecharse?","options":["ContaminaciÃ³n por metales pesados","ProducciÃ³n de oxÃ­geno","ReducciÃ³n del COâ‚‚","DesalinizaciÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© acciÃ³n ayuda a reducir el impacto de las baterÃ­as en el ambiente?","options":["Enterrarlas","Reciclarlas","Quemarlas","Usarlas indefinidamente"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© beneficio tienen las baterÃ­as de litio sobre las de plomo-Ã¡cido?","options":["Son mÃ¡s pesadas","Tienen mayor densidad de energÃ­a","Tienen menos capacidad","Se descargan mÃ¡s rÃ¡pido"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© caracterÃ­stica hace valiosas a las baterÃ­as recargables?","options":["Bajo costo de fabricaciÃ³n","ReutilizaciÃ³n varias veces","ProducciÃ³n de carbÃ³n","GeneraciÃ³n de agua"],"correctIndex":1,"points":10},
{"text":"Â¿CuÃ¡l es el principal gas de efecto invernadero?","options":["OxÃ­geno","DiÃ³xido de carbono","NitrÃ³geno","Helio"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© consecuencia provoca el deshielo de los polos?","options":["Aumento del nivel del mar","ReducciÃ³n de COâ‚‚","ExpansiÃ³n de desiertos","MÃ¡s energÃ­a solar"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© evento climÃ¡tico extremo se vuelve mÃ¡s comÃºn con el calentamiento global?","options":["Lluvias normales","SequÃ­as e inundaciones","Estaciones regulares","Aumento de cosechas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© actividad humana incrementa mÃ¡s las emisiones de COâ‚‚?","options":["Agricultura","Quema de combustibles fÃ³siles","ProducciÃ³n de energÃ­a solar","Caminatas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© documento internacional busca limitar el aumento de temperatura a 2 Â°C?","options":["Protocolo de Montreal","Acuerdo de ParÃ­s","DeclaraciÃ³n de RÃ­o","Agenda 2030"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de mÃ¡quina es una palanca?","options":["MÃ¡quina compuesta","MÃ¡quina simple","Motor elÃ©ctrico","Turbina"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© ejemplo clÃ¡sico muestra el tornillo de ArquÃ­medes?","options":["Extraer agua","Generar electricidad","Medir tiempo","Reproducir sonido"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ley fÃ­sica explica la conservaciÃ³n de energÃ­a en una polea?","options":["Ley de la Gravedad","Principio de conservaciÃ³n de la energÃ­a","Segunda Ley de Newton","Ley de Pascal"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© funciÃ³n tienen las presas hidroelÃ©ctricas?","options":["Controlar el calor","Generar electricidad con agua","Producir viento","Guardar petrÃ³leo"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© instrumento demuestra el principio de conservaciÃ³n de energÃ­a con bolas suspendidas?","options":["Balanza de Newton","Tornillo de ArquÃ­medes","Palanca romana","PÃ©ndulo magnÃ©tico"],"correctIndex":0,"points":10},
{"text":"Â¿En quÃ© estado mexicano se ubica la planta solar mÃ¡s grande de LatinoamÃ©rica?","options":["Sonora","Chiapas","Veracruz","Jalisco"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© recurso aprovecha la planta geotÃ©rmica de Cerro Prieto (BC)?","options":["Calor interno de la Tierra","RÃ­os","Viento","Sol"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© estado mexicano destaca por el uso de energÃ­a eÃ³lica?","options":["Oaxaca","Tabasco","Puebla","Campeche"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© central mexicana genera energÃ­a a partir del agua de rÃ­os?","options":["Laguna Verde","ChicoasÃ©n","Cerro Prieto","Sonora Solar"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© porcentaje de electricidad en MÃ©xico proviene de energÃ­as limpias aproximadamente?","options":["10%","30%","50%","70%"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© cientÃ­fico formulÃ³ la ecuaciÃ³n E=mcÂ²?","options":["Newton","Einstein","Volta","Faraday"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© unidad se usa para medir energÃ­a elÃ©ctrica?","options":["Voltio","Watt-hora","Newton","Julio"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© dispositivo mide el consumo de energÃ­a en casa?","options":["TermÃ³metro","Medidor elÃ©ctrico","DinamÃ³metro","Balanza"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© corriente elÃ©ctrica fluye en una sola direcciÃ³n?","options":["Corriente alterna","Corriente continua","Corriente mixta","Corriente rotatoria"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© invento permitiÃ³ la distribuciÃ³n masiva de electricidad en el siglo XIX?","options":["Bombilla","Transformador","Pila seca","Radio"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© acciÃ³n en el hogar reduce el consumo elÃ©ctrico?","options":["Dejar luces encendidas","Usar focos LED","Usar mÃ¡s electrodomÃ©sticos","Abrir refrigerador seguido"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© transporte ayuda a disminuir emisiones contaminantes?","options":["Auto particular","Bicicleta","Moto de gasolina","AviÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© prÃ¡ctica ayuda al ahorro de agua y energÃ­a en casa?","options":["Duchas largas","Reutilizar agua","Lavar con manguera","Dejar llaves abiertas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© energÃ­a se fomenta al instalar paneles en techos?","options":["Solar","HidrÃ¡ulica","Nuclear","CarbÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ejemplo de energÃ­a renovable puedes aprovechar en casa?","options":["Motor de gasolina","Calentador solar","Generador a carbÃ³n","Tanque de gas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tecnologÃ­a se investiga como sustituto de los combustibles fÃ³siles?","options":["FusiÃ³n nuclear","Motores de vapor","CarbÃ³n mineral","Gasolina sintÃ©tica"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© innovaciÃ³n se busca en paneles solares de prÃ³xima generaciÃ³n?","options":["Ser mÃ¡s pesados","Mayor eficiencia","Mayor contaminaciÃ³n","Menor durabilidad"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de automÃ³viles ayudan a reducir emisiones de COâ‚‚?","options":["Gasolina","ElÃ©ctricos","Diesel","CarbÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© fuente renovable se planea usar en el espacio para estaciones orbitales?","options":["Solar","Nuclear","HidrÃ¡ulica","CarbÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© acciÃ³n global es clave para un futuro energÃ©tico sustentable?","options":["CooperaciÃ³n internacional","Aumento de carbÃ³n","MÃ¡s consumo de petrÃ³leo","DestrucciÃ³n de bosques"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© es la biomasa?","options":["Materia plÃ¡stica","Materia orgÃ¡nica usada como energÃ­a","Minerales fÃ³siles","Rocas volcÃ¡nicas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© material se usa como ejemplo clÃ¡sico de biomasa en una fogata?","options":["CarbÃ³n mineral","LeÃ±a","Gas natural","PetrÃ³leo"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de residuos agrÃ­colas pueden aprovecharse como biomasa?","options":["Hierro y acero","MaÃ­z, soya y caÃ±a de azÃºcar","Cemento y ladrillo","Vidrio reciclado"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de desechos tambiÃ©n se consideran biomasa?","options":["Desechos plÃ¡sticos","Desechos sÃ³lidos como papel y algodÃ³n","Desechos metÃ¡licos","Desechos radiactivos"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© animal produce estiÃ©rcol usado como biomasa?","options":["Perros","Vacas","Peces","Aves"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de biomasa se obtiene de residuos orgÃ¡nicos urbanos?","options":["Biomasa industrial","Biomasa agrÃ­cola","Biomasa municipal","Biomasa ganadera"],"correctIndex":2,"points":10},
 {"text":"Â¿CÃ³mo se puede convertir directamente la biomasa en energÃ­a?","options":["QuemÃ¡ndola","CongelÃ¡ndola","TriturÃ¡ndola","SecÃ¡ndola"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© proceso biolÃ³gico transforma la biomasa en biogÃ¡s?","options":["CombustiÃ³n","FermentaciÃ³n anaerobia","FotosÃ­ntesis","EvaporaciÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© proceso permite producir combustibles lÃ­quidos, sÃ³lidos o gaseosos a partir de biomasa?","options":["CombustiÃ³n nuclear","ConversiÃ³n termoquÃ­mica","EvaporaciÃ³n solar","DesalinizaciÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de energÃ­a se genera al quemar biomasa?","options":["EnergÃ­a solar","Calor","EnergÃ­a eÃ³lica","EnergÃ­a hidrÃ¡ulica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© gas se asocia con la biomasa ganadera?","options":["COâ‚‚","CHâ‚„ (metano)","Nâ‚‚","Oâ‚ƒ"],"correctIndex":1,"points":10},
{"text":"Â¿De dÃ³nde se obtiene el metano para la biomasa ganadera?","options":["De los plÃ¡sticos reciclados","De las heces animales","De la madera","De las algas marinas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de plantas producen biomasa agrÃ­cola?","options":["Plantas oleaginosas","Plantas acuÃ¡ticas","Plantas ornamentales","Plantas medicinales"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ejemplos de plantas oleaginosas se mencionan para biomasa?","options":["MaÃ­z y frijol","Girasol, coco y soya","Cebolla y ajo","Trigo y arroz"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© combustible se obtiene a partir de biomasa agrÃ­cola?","options":["CarbÃ³n vegetal","BiodiÃ©sel","Gasolina","Etanol"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© caracterÃ­stica tiene el biodiÃ©sel frente a otros combustibles?","options":["Es mÃ¡s tÃ³xico","Menos tÃ³xico","Menos renovable","No se degrada"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© residuos de la industria del vino pueden usarse para biocombustibles?","options":["Botellas y corchos","Bagazo y pepitas de uva","Tapones metÃ¡licos","Agua residual"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© efecto ambiental ayuda a reducir la biomasa?","options":["La erosiÃ³n del suelo","Las emisiones de COâ‚‚","La formaciÃ³n de ozono","El ciclo del agua"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© ventaja tiene el biogÃ¡s sobre otros combustibles?","options":["Es fÃ³sil","Es renovable","Es mÃ¡s caro","Es mÃ¡s contaminante"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© energÃ­a produce al quemar biogÃ¡s en turbinas?","options":["EnergÃ­a solar","EnergÃ­a elÃ©ctrica","EnergÃ­a hidrÃ¡ulica","EnergÃ­a eÃ³lica"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© se puede usar el biogÃ¡s ademÃ¡s de electricidad?","options":["Como fertilizante","Como combustible para transporte","Para fabricar plÃ¡sticos","Para producir cemento"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© sector aprovecha la biomasa agrÃ­cola?","options":["GanaderÃ­a","Agricultura","MinerÃ­a","Pesca"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© son las ecotecnias?","options":["Maquinarias pesadas","Dispositivos tecnolÃ³gicos para equilibrio naturaleza-sociedad","Industrias quÃ­micas","Aparatos elÃ©ctricos"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© beneficios ofrecen las ecotecnias?","options":["ContaminaciÃ³n","Prosperidad de las personas y protecciÃ³n ambiental","MÃ¡s gasto energÃ©tico","Menor eficiencia"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© caracterÃ­stica importante tienen las ecotecnias?","options":["Ser universales sin importar la regiÃ³n","Adaptarse a las comunidades locales","Depender del petrÃ³leo","Ser de un solo uso"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© factores se consideran al instalar ecotecnias?","options":["Temperatura, precipitaciÃ³n, radiaciÃ³n solar","Color del suelo","Edad de la comunidad","Cantidad de automÃ³viles"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ayudan a restaurar las ecotecnias?","options":["La minerÃ­a","El equilibrio entre naturaleza y sociedad","El consumo de carbÃ³n","La deforestaciÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© transforma un generador eÃ³lico?","options":["EnergÃ­a hidrÃ¡ulica en calor","EnergÃ­a cinÃ©tica del viento en electricidad","EnergÃ­a solar en calor","EnergÃ­a quÃ­mica en gas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© hacen girar las aspas o hÃ©lices de un aerogenerador?","options":["Agua","Viento","Luz solar","Combustible fÃ³sil"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© estados de MÃ©xico se desarrollan aerogeneradores de baja potencia?","options":["Veracruz y Tabasco","Chiapas y Oaxaca","Jalisco y Puebla","Sonora y Baja California"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© dispositivos permiten transmitir la energÃ­a mecÃ¡nica en un generador eÃ³lico?","options":["Cables elÃ©ctricos","Engranajes","Imanes","Tubos de agua"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de energÃ­a aprovechan directamente los aerogeneradores?","options":["Solar","CinÃ©tica del viento","HidrÃ¡ulica","QuÃ­mica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© transforman las celdas fotovoltaicas?","options":["EnergÃ­a solar en energÃ­a elÃ©ctrica","EnergÃ­a tÃ©rmica en calor","EnergÃ­a hidrÃ¡ulica en vapor","EnergÃ­a quÃ­mica en sonido"],"correctIndex":0,"points":10},
{"text":"Â¿En quÃ© se basan las celdas solares comunes?","options":["Efecto electromagnÃ©tico","Efecto fotovoltaico","Efecto gravitacional","Efecto mecÃ¡nico"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© produce la luz solar en el semiconductor de la celda?","options":["Corriente alterna","Diferencia de voltaje","EnergÃ­a tÃ©rmica","OxÃ­geno"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© hace el voltaje generado en la celda?","options":["Transporta agua","Conduce corriente en un circuito externo","Produce aire","Mueve turbinas hidrÃ¡ulicas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© utilidad tiene la corriente generada en celdas solares?","options":["Producir trabajo Ãºtil","Calentar leÃ±a","Elevar temperatura ambiental","Disolver agua"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© porcentaje de energÃ­a aprovechan los motores de combustiÃ³n interna?","options":["100%","25%","50%","75%"],"correctIndex":1,"points":10},
{"text":"Â¿En quÃ© se transforma el resto de la energÃ­a en un motor de combustiÃ³n?","options":["Agua","Calor","OxÃ­geno","Metano"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© gas producen los motores de combustiÃ³n que afecta al clima?","options":["OxÃ­geno","DiÃ³xido de carbono","NitrÃ³geno","ArgÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de transporte reduce entre 30 y 40% el consumo energÃ©tico respecto a gasolina?","options":["Transporte aÃ©reo","Transporte elÃ©ctrico","Transporte marÃ­timo","Transporte fÃ³sil"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© efecto tienen los motores elÃ©ctricos sobre el medio ambiente?","options":["Mayor contaminaciÃ³n","Menor impacto negativo","Incremento de gases","Aumento de deforestaciÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© buscan los transportes hÃ­bridos?","options":["Combinar motor de gasolina y elÃ©ctrico","Usar solo carbÃ³n","Evitar energÃ­a solar","Usar aire comprimido"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© diferencia a un auto elÃ©ctrico de uno tradicional?","options":["Mayor consumo de gasolina","Funciona con baterÃ­as","Produce mÃ¡s COâ‚‚","Usa carbÃ³n mineral"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tecnologÃ­a permite el salto en transportes para reducir impacto ambiental?","options":["Motores a carbÃ³n","Salto tecnolÃ³gico","Motores de vapor","Gasolina ecolÃ³gica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© porcentaje de ahorro energÃ©tico ofrecen los autos elÃ©ctricos frente a gasolina?","options":["5â€“10%","30â€“40%","50â€“60%","70â€“80%"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© impacto global tiene el cambio a energÃ­as limpias en transporte?","options":["MÃ¡s contaminaciÃ³n","ReducciÃ³n de gases de efecto invernadero","Aumento del calentamiento","MÃ¡s uso de petrÃ³leo"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© otra fuente renovable ademÃ¡s de biomasa y eÃ³lica aparece en las imÃ¡genes?","options":["Nuclear","Solar (fotovoltaica)","CarbÃ³n","PetrÃ³leo"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© dispositivo transforma energÃ­a del sol directamente en electricidad?","options":["Aerogenerador","Celda fotovoltaica","Turbina hidrÃ¡ulica","Motor de gasolina"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© recurso natural es indispensable para la energÃ­a eÃ³lica?","options":["Agua","Viento","Fuego","PetrÃ³leo"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tecnologÃ­a busca equilibrar necesidades humanas y la naturaleza?","options":["Ecotecnias","Motores fÃ³siles","Industrias quÃ­micas","EnergÃ­a nuclear"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se obtiene al usar residuos orgÃ¡nicos como energÃ­a?","options":["Combustibles sÃ³lidos, lÃ­quidos o gaseosos","Basura","Minerales","EnergÃ­a nuclear"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© es la biomasa?","options":["Materia orgÃ¡nica usada como fuente de energÃ­a","Rocas y minerales","EnergÃ­a solar","Agua de los rÃ­os"],"correctIndex":0,"points":10},
{"text":"Â¿CuÃ¡l de estos materiales es considerado biomasa?","options":["Papel reciclado","Hierro","PetrÃ³leo","Gas natural"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de energÃ­a se obtiene al quemar biomasa directamente?","options":["Calor","EnergÃ­a nuclear","EnergÃ­a hidrÃ¡ulica","Electricidad solar"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se puede producir mediante la conversiÃ³n termoquÃ­mica de la biomasa?","options":["Combustibles","Minerales","PetrÃ³leo","Uranio"],"correctIndex":0,"points":10},
{"text":"Â¿CuÃ¡l de estos es un ejemplo de biomasa agrÃ­cola?","options":["Girasol","Gas natural","CarbÃ³n mineral","PetrÃ³leo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© gas se produce en biodigestores a partir de estiÃ©rcol?","options":["Metano (CH4)","OxÃ­geno","HidrÃ³geno","NitrÃ³geno"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se usa para producir biodiÃ©sel a partir de biomasa agrÃ­cola?","options":["Aceites vegetales","CarbÃ³n","Arena","Oro"],"correctIndex":0,"points":10},
{"text":"Â¿CuÃ¡l es un ejemplo de biomasa ganadera?","options":["EstiÃ©rcol de vaca","Gas propano","CarbÃ³n mineral","PetrÃ³leo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de energÃ­a genera el biogÃ¡s al ser quemado?","options":["ElÃ©ctrica y tÃ©rmica","EnergÃ­a nuclear","Solar","Mareomotriz"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© residuo de la industria vinÃ­cola se usa para biocombustibles?","options":["Pepitas de uva","CarbÃ³n","Gas natural","Uranio"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ventaja tienen los biocombustibles respecto a los fÃ³siles?","options":["Menor toxicidad","Mayor contaminaciÃ³n","Escasez de materia prima","Son no renovables"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© proceso convierte desechos en metano?","options":["DigestiÃ³n anaerobia","FotosÃ­ntesis","CombustiÃ³n nuclear","FusiÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se obtiene del bagazo de uva para energÃ­a?","options":["Biocombustibles","CarbÃ³n","PetrÃ³leo","Uranio"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© aparato aprovecha el biogÃ¡s para producir electricidad?","options":["Turbina","Panel solar","Reactor nuclear","BaterÃ­a"],"correctIndex":0,"points":10},
{"text":"Â¿CuÃ¡l de estos NO es biomasa?","options":["Algas","EstiÃ©rcol","PetrÃ³leo","CaÃ±a de azÃºcar"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© son las ecotecnias?","options":["Dispositivos tecnolÃ³gicos que restauran el equilibrio entre naturaleza y sociedad","Plantas medicinales","MÃ¡quinas nucleares","Combustibles fÃ³siles"],"correctIndex":0,"points":10},
{"text":"Â¿CuÃ¡l es una caracterÃ­stica de las ecotecnias?","options":["Se adaptan a las culturas y condiciones locales","Solo funcionan en paÃ­ses ricos","Requieren petrÃ³leo","Son desechables"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© factores se consideran en una ecotecnia?","options":["Temperatura, precipitaciÃ³n y radiaciÃ³n solar","Oro y plata","Combustibles fÃ³siles","Dinero en efectivo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© beneficio aportan las ecotecnias?","options":["Prosperidad de las comunidades","Mayor contaminaciÃ³n","Escasez de energÃ­a","Desempleo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© energÃ­a aprovecha un generador eÃ³lico?","options":["EnergÃ­a cinÃ©tica del viento","EnergÃ­a nuclear","EnergÃ­a solar","EnergÃ­a geotÃ©rmica"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© hacen las aspas de un generador eÃ³lico?","options":["Hacen girar un eje conectado a un generador","Producen calor","Extraen petrÃ³leo","Capturan COâ‚‚"],"correctIndex":0,"points":10},
{"text":"Â¿DÃ³nde se desarrollan aerogeneradores de baja potencia en MÃ©xico?","options":["Chiapas y Oaxaca","Sonora y Baja California","Quintana Roo","Durango"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© dispositivo transforma la energÃ­a solar en electricidad?","options":["Celdas fotovoltaicas","Turbinas hidrÃ¡ulicas","Generadores diÃ©sel","Focos incandescentes"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© principio usan las celdas solares?","options":["Efecto fotovoltaico","FisiÃ³n nuclear","CombustiÃ³n","Magnetismo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© produce la diferencia de voltaje en una celda solar?","options":["Corriente elÃ©ctrica","Calor","Agua","CombustiÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿Para quÃ© sirve un secador solar?","options":["Deshidratar y conservar alimentos","Generar electricidad","Producir agua potable","Fabricar metales"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© productos se pueden secar con un secador solar?","options":["Mango, plÃ¡tano, cafÃ©","PetrÃ³leo, gas, carbÃ³n","Metales","Agua"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ventaja ofrecen los secadores solares?","options":["Mejoran la calidad y reducen el tiempo de secado","Producen COâ‚‚","Aumentan la humedad","Consumen gas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de estructura usan los secadores solares?","options":["Prefabricada y resistente a la intemperie","De plÃ¡stico","De carbÃ³n","Nuclear"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© reducen las estufas ecolÃ³gicas?","options":["Emisiones de COâ‚‚","Emisiones de oxÃ­geno","ProducciÃ³n de agua","Luz solar"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© Ã­ndice cumplen las estufas ecolÃ³gicas segÃºn la OMS?","options":["EstÃ¡n por debajo de los lÃ­mites permisibles","EstÃ¡n por encima de lo permitido","Emiten mÃ¡s gases","No cumplen normas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© combustibles pueden usar las estufas ecolÃ³gicas ademÃ¡s de leÃ±a?","options":["BiogÃ¡s y aserrÃ­n","Uranio","Gasolina","CarbÃ³n mineral"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© beneficio social tienen las estufas ecolÃ³gicas?","options":["Reunir a la familia alrededor del calor","Contaminar mÃ¡s","Gastar mÃ¡s dinero","Producir humo tÃ³xico"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© aprovechan las estufas ecolÃ³gicas en su diseÃ±o?","options":["Gases de combustiÃ³n para ahumar alimentos","EnergÃ­a nuclear","EnergÃ­a solar","Aire frÃ­o"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© funciÃ³n adicional pueden tener las estufas ecolÃ³gicas?","options":["Calentar agua en un termotanque","Generar electricidad nuclear","Producir gasolina","Enfriar alimentos"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© usaban los humanos prehistÃ³ricos para iluminarse?","options":["Fuego","CarbÃ³n","Gas natural","Uranio"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© combustible se usÃ³ en lÃ¡mparas antiguas?","options":["Aceite","PlÃ¡stico","Gasolina","Oro"],"correctIndex":0,"points":10},
{"text":"Â¿QuiÃ©n presentÃ³ la bombilla incandescente en 1879?","options":["Thomas Alva Edison","Nikola Tesla","Alessandro Volta","Isaac Newton"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© significa LED?","options":["Light Emitting Diode","Light Energy Device","Low Energy Device","Light Electric Drive"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ventaja tienen los focos LED frente a los incandescentes?","options":["Consumen 88% menos energÃ­a","Emiten mÃ¡s calor","Duran menos tiempo","Contaminan mÃ¡s"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© revolucionÃ³ la forma de iluminar el mundo en el siglo XIX?","options":["Foco incandescente","Gasolina","CarbÃ³n","PetrÃ³leo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© material se usaba en velas antiguas?","options":["Cera","Uranio","Gas","CarbÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© representan los experimentos con bicis y focos en museos?","options":["Diferencia de energÃ­a entre incandescente y LED","ProducciÃ³n de COâ‚‚","CombustiÃ³n de gas","EnergÃ­a nuclear"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© dispositivo revolucionÃ³ despuÃ©s de los incandescentes?","options":["LED","CarbÃ³n","PetrÃ³leo","Uranio"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© significa que el LED aÃºn estÃ¡ en investigaciÃ³n?","options":["Que puede mejorar con nuevas posibilidades","Que no funciona","Que contamina mÃ¡s","Que estÃ¡ prohibido"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© elemento es el mÃ¡s abundante en el universo?","options":["HidrÃ³geno","OxÃ­geno","Helio","Carbono"],"correctIndex":0,"points":10},
{"text":"Â¿Por quÃ© no se encuentra el hidrÃ³geno libre en la Tierra?","options":["Porque debe producirse a partir de otras fuentes","Porque no existe","Porque se transforma en helio","Porque es sÃ³lido"],"correctIndex":0,"points":10},
{"text":"Â¿CÃ³mo se le denomina al hidrÃ³geno en energÃ­a?","options":["Portador de energÃ­a","Combustible fÃ³sil","EnergÃ­a nuclear","EnergÃ­a solar"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© usos energÃ©ticos tiene el hidrÃ³geno?","options":["Refinar petrÃ³leo, propulsar cohetes, generar electricidad","Producir oro","Hacer carbÃ³n","Obtener gas natural"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© busca mejorar la innovaciÃ³n en hidrÃ³geno?","options":["La eficiencia de las celdas de combustible","La extracciÃ³n de carbÃ³n","La combustiÃ³n de petrÃ³leo","La energÃ­a nuclear"],"correctIndex":0,"points":10},
{"text":"Â¿Desde quÃ© aÃ±o la NASA usa hidrÃ³geno como combustible?","options":["1950","1970","1985","2000"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© impulsa el hidrÃ³geno en la NASA?","options":["Cohetes","Submarinos","Aviones comerciales","SatÃ©lites"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tecnologÃ­a permite separar hidrÃ³geno y oxÃ­geno?","options":["ElectrÃ³lisis","CombustiÃ³n","DigestiÃ³n","Magnetismo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© gas se observa como burbujas en la electrÃ³lisis?","options":["HidrÃ³geno","Helio","NitrÃ³geno","DiÃ³xido de carbono"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ventaja tiene el hidrÃ³geno como energÃ­a?","options":["Puede almacenarse y transportarse","Es no renovable","Genera contaminaciÃ³n","Se agota fÃ¡cilmente"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© producen los automÃ³viles de combustiÃ³n?","options":["DiÃ³xido de carbono","OxÃ­geno","HidrÃ³geno","Agua"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© porcentaje de energÃ­a aprovecha un motor de combustiÃ³n interna?","options":["25%","50%","75%","100%"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de motores producen menos emisiones contaminantes?","options":["Motores elÃ©ctricos","Motores a gasolina","Motores a diÃ©sel","Motores a carbÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ahorro ofrecen los autos elÃ©ctricos frente a gasolina?","options":["30-40%","5%","10%","90%"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© problema generan los motores tradicionales?","options":["Calentamiento global","GeneraciÃ³n de oxÃ­geno","EnergÃ­a limpia","Agua potable"],"correctIndex":0,"points":10},
{"text":"Â¿CuÃ¡ntos automÃ³viles circulan en el mundo aproximadamente?","options":["MÃ¡s de 500 millones","10 millones","100 millones","1 millÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se considera â€œenemigo pÃºblicoâ€ en transporte?","options":["Motores de combustiÃ³n interna","Paneles solares","EnergÃ­a eÃ³lica","Agua"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© gas de efecto invernadero producen los coches?","options":["COâ‚‚","Helio","NitrÃ³geno","OxÃ­geno"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de transporte es una soluciÃ³n sustentable?","options":["ElÃ©ctrico","CarbÃ³n","PetrÃ³leo","Gas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© impacto tienen los autos en el cambio climÃ¡tico?","options":["Elevan la temperatura global","Reducen el COâ‚‚","Generan oxÃ­geno","Producen energÃ­a solar"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ocurre al encender un foco en casa?","options":["Recibimos energÃ­a instantÃ¡nea","Se quema gas","Se produce petrÃ³leo","Se genera viento"],"correctIndex":0,"points":10},
{"text":"Â¿DÃ³nde se produce generalmente la energÃ­a?","options":["En centrales elÃ©ctricas","En la cocina","En rÃ­os pequeÃ±os","En autos"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de centrales producen energÃ­a?","options":["HidroelÃ©ctricas, termoelÃ©ctricas y eÃ³licas","Bancos","FÃ¡bricas de ropa","Cuevas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se necesita para llevar energÃ­a a la poblaciÃ³n?","options":["Un sistema de transmisiÃ³n","CarbÃ³n","PetrÃ³leo","Gasolina"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© transporta la electricidad para minimizar pÃ©rdidas?","options":["Alto voltaje","Bajo voltaje","Calor","Agua"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se transforma en la subestaciÃ³n?","options":["Alto voltaje en bajo voltaje","Agua en gas","CarbÃ³n en petrÃ³leo","Fuego en luz"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© conecta la central elÃ©ctrica con la poblaciÃ³n?","options":["Cables","Tubos","Pozos","LÃ¡mparas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© pasa si no hubiera cables elÃ©ctricos?","options":["No llegarÃ­a energÃ­a a los hogares","Se producirÃ­a mÃ¡s petrÃ³leo","HabrÃ¡ mÃ¡s luz natural","Se genera gas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ventaja tiene usar alto voltaje en transmisiÃ³n?","options":["Reduce pÃ©rdidas de energÃ­a","Genera mÃ¡s calor","Aumenta contaminaciÃ³n","Produce agua"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se reparte en la compaÃ±Ã­a de luz local?","options":["EnergÃ­a de bajo voltaje","Gas natural","CarbÃ³n","Agua"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© desafÃ­o tiene el abasto mundial de energÃ­a?","options":["Cubrir a la poblaciÃ³n creciente","Producir ropa","Crear comida","Generar oro"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© debe tambiÃ©n considerar el abasto energÃ©tico?","options":["ConservaciÃ³n de recursos naturales","ProducciÃ³n de petrÃ³leo","Uso de carbÃ³n","ContaminaciÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© escenario plantea el World Energy Council para 2050?","options":["Jazz y SinfonÃ­a","Pop y Rock","Gas y PetrÃ³leo","CarbÃ³n y Uranio"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© caracteriza al escenario Jazz?","options":["Enfoque en consumo y mercado","Uso de carbÃ³n","ExclusiÃ³n de renovables","Cierre de empresas"],"correctIndex":0,"points":10},
{"text":"Â¿QuiÃ©nes son los actores principales en el escenario Jazz?","options":["Empresas multinacionales y bancos","Agricultores","Gobiernos locales","Escuelas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© caracteriza al escenario SinfonÃ­a?","options":["Consenso para sostenibilidad","Uso de carbÃ³n","ExplotaciÃ³n minera","PetrÃ³leo abundante"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© actores destacan en SinfonÃ­a?","options":["Gobiernos, ONG y votantes ambientalistas","Empresas textiles","Gasolineras","Mineros"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© busca la sostenibilidad energÃ©tica?","options":["Seguridad ambiental y energÃ©tica","Extraer petrÃ³leo","Producir carbÃ³n","Generar gas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© papel tienen los consumidores en Jazz?","options":["Elegir las mejores fuentes de energÃ­a","Comprar petrÃ³leo","Explotar carbÃ³n","Vender uranio"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© papel tienen los gobiernos en SinfonÃ­a?","options":["Impulsar renovables con subsidios","Producir mÃ¡s carbÃ³n","Aumentar contaminaciÃ³n","Limitar energÃ­a"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ventaja tienen las energÃ­as renovables?","options":["Se regeneran naturalmente","Se agotan rÃ¡pido","Son fÃ³siles","Son contaminantes"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ejemplos de energÃ­a renovable existen?","options":["Solar, eÃ³lica, hidrÃ¡ulica","CarbÃ³n, gas y petrÃ³leo","Uranio y diÃ©sel","Ninguno"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ejemplos de energÃ­as no renovables existen?","options":["CarbÃ³n, gas natural, petrÃ³leo","Solar, eÃ³lica","HidrÃ¡ulica y geotÃ©rmica","Biomasa"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© problema generan las no renovables?","options":["Cambio climÃ¡tico","Aumento de oxÃ­geno","DisminuciÃ³n de calor","EnergÃ­a limpia"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© pasarÃ¡ si seguimos usando no renovables al mismo ritmo?","options":["Se agotarÃ¡n las reservas","HabrÃ¡ mÃ¡s oxÃ­geno","HabrÃ¡ menos calor","No pasarÃ¡ nada"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© recurso de MÃ©xico es privilegiado en renovables?","options":["Solar, eÃ³lica y geotÃ©rmica","CarbÃ³n","Gas natural","Uranio"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© instituciones impulsan energÃ­as renovables en MÃ©xico?","options":["UNAM y centros de energÃ­a","Gasolineras","Bancos","FÃ¡bricas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© ventaja tienen los sistemas solares tÃ©rmicos?","options":["Calientan agua","Producen carbÃ³n","Generan petrÃ³leo","Transforman gas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© recurso natural aprovecha la energÃ­a mareomotriz?","options":["Movimiento del mar","CarbÃ³n","Gas natural","PetrÃ³leo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© recurso natural aprovecha la energÃ­a hidrÃ¡ulica?","options":["RÃ­os","CarbÃ³n","Gas","PetrÃ³leo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© beneficio tiene reciclar papel?","options":["Ahorrar Ã¡rboles","Producir gas","Generar petrÃ³leo","Consumir carbÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© contenedor se usa para reciclar vidrio?","options":["Verde","Azul","Amarillo","Gris"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© contenedor se usa para reciclar plÃ¡sticos y metales?","options":["Amarillo","Azul","Verde","Negro"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© contenedor se usa para reciclar papel y cartÃ³n?","options":["Azul","Verde","Amarillo","Rojo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© acciÃ³n ayuda al medio ambiente?","options":["Ahorrar agua y energÃ­a","Usar mÃ¡s plÃ¡sticos","Quemar basura","Desperdiciar comida"],"correctIndex":0,"points":10},
{"text":"Â¿Hace cuÃ¡nto tiempo ocurriÃ³ la Gran ExplosiÃ³n que dio origen al universo?","options":["4,500 millones de aÃ±os","10,000 millones de aÃ±os","13,800 millones de aÃ±os","2,000 millones de aÃ±os"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© se liberÃ³ en la Gran ExplosiÃ³n?","options":["EnergÃ­a potencial","Agua","OxÃ­geno","CarbÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© surgiÃ³ tras la Gran ExplosiÃ³n?","options":["Solo planetas","Materia, energÃ­a, espacio y tiempo","Ãšnicamente estrellas","Ãšnicamente galaxias"],"correctIndex":1,"points":10},
{"text":"Â¿CÃ³mo se denomina el inicio del universo?","options":["EvoluciÃ³n universal","Gran ExplosiÃ³n (Big Bang)","RadiaciÃ³n cÃ³smica","ExpansiÃ³n galÃ¡ctica"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© sucedÃ­a con el universo al enfriarse despuÃ©s del Big Bang?","options":["Se encogÃ­a","Se expandÃ­a","Se detenÃ­a","Se colapsaba"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© apareciÃ³ a medida que el universo se expandÃ­a y enfriaba?","options":["Estructuras cada vez mÃ¡s complejas","Ãšnicamente Ã¡tomos","Ãšnicamente gases","Meteoritos"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© caracterÃ­stica tiene el universo desde el Big Bang hasta hoy?","options":["Se mantiene en reposo","Se mantiene en contracciÃ³n","Se mantiene en expansiÃ³n","Se mantiene igual"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© tipo de energÃ­a se menciona como liberada en la Gran ExplosiÃ³n?","options":["EnergÃ­a elÃ©ctrica","EnergÃ­a cinÃ©tica","EnergÃ­a potencial","EnergÃ­a solar"],"correctIndex":2,"points":10},
{"text":"Â¿QuÃ© actividad sugiere el cartel para los visitantes?","options":["Dormir en el espacio","Observar el video","Comprar un libro","Jugar con maquetas"],"correctIndex":1,"points":10},
{"text":"Â¿CuÃ¡l es el tercer paso recomendado en el cartel de actividades?","options":["Escribir un resumen","Analizar y disfrutar el paseo a travÃ©s del cosmos","Construir un modelo del universo","Medir la radiaciÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© iniciÃ³ todo lo que conocemos en el cosmos?","options":["Una gran nube de polvo","La Gran ExplosiÃ³n","Un meteorito","Una supernova"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© se formÃ³ junto con la materia en el origen del universo?","options":["La Luna","EnergÃ­a, espacio y tiempo","Los continentes","Las montaÃ±as"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© comparaciÃ³n describe la rapidez del origen del universo?","options":["Como una tormenta","Como un abrir y cerrar de ojos","Como un rÃ­o fluyendo","Como una caminata"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© tipo de radiaciÃ³n se liberÃ³ en la Gran ExplosiÃ³n?","options":["Solar","De materia y radiaciÃ³n","Infrarroja","Microondas"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© sucede con el universo en la actualidad segÃºn el texto?","options":["Se contrae","Se mantiene en expansiÃ³n","Se detiene","Desaparece"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© edad se le calcula al universo?","options":["2,000 millones de aÃ±os","6,000 millones de aÃ±os","13,800 millones de aÃ±os","20,000 millones de aÃ±os"],"correctIndex":2,"points":10},
{"text":"Â¿CÃ³mo se llama al inicio violento del universo?","options":["Gran explosiÃ³n","Supernova universal","Colapso galÃ¡ctico","FusiÃ³n cÃ³smica"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© pasÃ³ cuando el universo comenzÃ³ a enfriarse?","options":["Se detuvo","Se expandiÃ³ y aparecieron estructuras complejas","Se contrajo","DesapareciÃ³"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© estructuras comenzaron a aparecer tras la expansiÃ³n?","options":["Estructuras cada vez mÃ¡s complejas","Solo Ã¡tomos simples","Solo estrellas gigantes","Solo agujeros negros"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© sugiere el cartel como primer paso de la experiencia en el museo?","options":["Leer un libro","Entrar al espacio de proyecciÃ³n","Escribir una reseÃ±a","Medir la gravedad"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© ocurre cuando la energÃ­a potencial se libera violentamente?","options":["Se forma un rÃ­o","Se origina materia y radiaciÃ³n","Se produce aire","Se genera un planeta"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© concepto estÃ¡ relacionado con el nacimiento del tiempo?","options":["La Gran ExplosiÃ³n","La Luna","El agua","La atmÃ³sfera"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© elemento NO se menciona como surgido en el Big Bang?","options":["Materia","EnergÃ­a","Espacio","Dinero"],"correctIndex":3,"points":10},
{"text":"Â¿QuÃ© frase describe mejor el inicio del universo?","options":["Fue lento y progresivo","Fue rÃ¡pido y violento","Fue silencioso y estable","Fue ordenado"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© proceso continÃºa desde el inicio del universo hasta hoy?","options":["ContracciÃ³n","ExpansiÃ³n","Estancamiento","ReducciÃ³n"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© significa la palabra \"cosmos\"?","options":["El conjunto del universo","Solo las estrellas","Solo los planetas","Solo los agujeros negros"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de estructuras surgieron con el tiempo en el universo?","options":["MÃ¡s complejas","MÃ¡s simples","MÃ¡s pequeÃ±as","MÃ¡s dÃ©biles"],"correctIndex":0,"points":10},
{"text":"Â¿CuÃ¡l fue la causa del origen del universo segÃºn la teorÃ­a expuesta?","options":["Cambio en un punto denso y caliente","ColisiÃ³n de planetas","CreaciÃ³n de la Tierra","ApariciÃ³n de galaxias"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© debemos hacer en el paso 2 de la experiencia segÃºn el cartel?","options":["Observar el video","Leer una guÃ­a","Contestar un examen","Medir estrellas"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© indica el cartel al final sobre el universo?","options":["Que se detuvo","Que sigue en expansiÃ³n","Que se contrajo","Que estÃ¡ vacÃ­o"],"correctIndex":1,"points":10},
{"text":"Â¿CuÃ¡l es la importancia del Big Bang?","options":["Dio origen a todo lo existente","CreÃ³ solo la Tierra","EncendiÃ³ el Sol","FormÃ³ los ocÃ©anos"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de materia existiÃ³ al inicio?","options":["Materia y radiaciÃ³n","PetrÃ³leo","Hierro","Hielo"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se originÃ³ con la Gran ExplosiÃ³n ademÃ¡s de la materia?","options":["EnergÃ­a","Agua","OxÃ­geno","CarbÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿CÃ³mo se encontraba el punto inicial del universo antes del Big Bang?","options":["Denso y caliente","FrÃ­o y vacÃ­o","DÃ©bil y oscuro","RÃ¡pido y ligero"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© propiedad mantiene hoy el universo segÃºn el texto?","options":["ExpansiÃ³n","ContracciÃ³n","DesapariciÃ³n","Equilibrio estÃ¡tico"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© fenÃ³meno dio lugar al espacio y al tiempo?","options":["La Gran ExplosiÃ³n","La lluvia de meteoritos","Una galaxia en rotaciÃ³n","Una estrella masiva"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© se necesita hacer en el paso 3 de la experiencia?","options":["Tomar notas","Analizar y disfrutar el paseo a travÃ©s del cosmos","Preguntar al guÃ­a","Buscar planetas"],"correctIndex":1,"points":10},
{"text":"Â¿CuÃ¡l de las siguientes NO es una consecuencia directa del Big Bang?","options":["Materia","Espacio","Tiempo","Dinero"],"correctIndex":3,"points":10},
{"text":"Â¿QuÃ© metÃ¡fora usa el cartel para la rapidez del inicio del universo?","options":["Como una lluvia","Como un abrir y cerrar de ojos","Como un trueno lejano","Como una sombra"],"correctIndex":1,"points":10},
{"text":"Â¿QuÃ© mantiene al universo en constante cambio?","options":["Su expansiÃ³n","La contracciÃ³n","La desapariciÃ³n","El equilibrio"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© debes evitar para no desequilibrar tu energÃ­a segÃºn el juego interactivo?","options":["Comer en exceso","Hacer ejercicio","Dormir bien","Beber agua"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© actividad fÃ­sica se recomienda para mantener el equilibrio energÃ©tico?","options":["Caminar o correr","Ver televisiÃ³n","Jugar videojuegos","Navegar en internet"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© debes hacer para equilibrar la energÃ­a que consumes?","options":["Realizar actividad fÃ­sica","Comer mÃ¡s","Dormir menos","Ver televisiÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© representa la barra de energÃ­a en el juego interactivo?","options":["Tu nivel de energÃ­a","Tu peso corporal","Tu edad","Tu altura"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© efecto tiene comer en exceso segÃºn el juego?","options":["Desequilibra tu energÃ­a","Aumenta tu energÃ­a","Mejora tu salud","Te hace mÃ¡s fuerte"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© debes hacer si tu barra de energÃ­a estÃ¡ baja en el juego?","options":["Hacer ejercicio","Comer mÃ¡s comida chatarra","Dormir menos","Ver televisiÃ³n"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© tipo de alimentos debes evitar para mantener el equilibrio energÃ©tico?","options":["Comida chatarra y azÃºcares en exceso","Frutas y verduras","ProteÃ­nas magras","Granos enteros"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© beneficio tiene realizar actividad fÃ­sica regularmente?","options":["Equilibrar la energÃ­a consumida y gastada","Aumentar el apetito por comida chatarra","Disminuir la energÃ­a disponible","Generar mÃ¡s estrÃ©s"],"correctIndex":0,"points":10},
{"text":"Â¿QuÃ© representa el juego interactivo sobre energÃ­a y salud?","options":["La importancia del equilibrio entre consumo y gasto energÃ©tico","La cantidad de comida que debes comer al dÃ­a","El tiempo que debes dormir cada noche","La cantidad de agua que debes beber"],"correctIndex":0,"points":10}
]


;
