-- Script para conectar Sala Energia con las demas salas en Supabase.
-- Ejecutar en: Supabase Dashboard > SQL Editor.

create extension if not exists "pgcrypto";

create table if not exists public.salas (
  id uuid primary key,
  nombre text not null,
  slug text unique,
  descripcion text,
  created_at timestamptz not null default now()
);

alter table public.salas
  add column if not exists nombre text,
  add column if not exists slug text,
  add column if not exists descripcion text,
  add column if not exists created_at timestamptz not null default now();

create table if not exists public."Ganadores" (
  id bigint generated by default as identity primary key,
  nombre text,
  correo text,
  telefono text,
  folio text unique not null,
  valido_desde timestamptz,
  valido_hasta timestamptz,
  estatus text not null default 'activo',
  tipo_entrada text,
  ubicacion text,
  created_at timestamptz not null default now()
);

alter table public."Ganadores"
  add column if not exists nombre text,
  add column if not exists correo text,
  add column if not exists telefono text,
  add column if not exists folio text,
  add column if not exists valido_desde timestamptz,
  add column if not exists valido_hasta timestamptz,
  add column if not exists estatus text not null default 'activo',
  add column if not exists tipo_entrada text,
  add column if not exists ubicacion text,
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  sala_id uuid references public.salas(id) on update cascade on delete set null,
  participante_id bigint references public."Ganadores"(id) on update cascade on delete set null,
  started_at timestamptz,
  finished_at timestamptz,
  puntaje_total integer not null default 0,
  num_correctas integer not null default 0,
  num_preguntas integer not null default 0,
  estatus text not null default 'activo',
  ubicacion text,
  created_at timestamptz not null default now()
);

alter table public.quizzes
  add column if not exists sala_id uuid,
  add column if not exists participante_id bigint,
  add column if not exists started_at timestamptz,
  add column if not exists finished_at timestamptz,
  add column if not exists puntaje_total integer not null default 0,
  add column if not exists num_correctas integer not null default 0,
  add column if not exists num_preguntas integer not null default 0,
  add column if not exists estatus text not null default 'activo',
  add column if not exists ubicacion text,
  add column if not exists created_at timestamptz not null default now();

insert into public.salas (id, nombre, slug, descripcion)
values (
  '08a6cc96-5323-42e0-89df-77a8c36e9705',
  'Sala Energia',
  'energia',
  'Sala de Energia'
)
on conflict (id) do update set
  nombre = excluded.nombre,
  slug = excluded.slug,
  descripcion = excluded.descripcion;

create index if not exists idx_quizzes_sala_id
  on public.quizzes (sala_id);

create index if not exists idx_quizzes_participante_id
  on public.quizzes (participante_id);

create index if not exists idx_quizzes_started_at
  on public.quizzes (started_at desc);

create index if not exists idx_ganadores_folio
  on public."Ganadores" (folio);

create index if not exists idx_ganadores_estatus
  on public."Ganadores" (estatus);

alter table public.salas enable row level security;
alter table public.quizzes enable row level security;
alter table public."Ganadores" enable row level security;

drop policy if exists salas_select_public on public.salas;
create policy salas_select_public
on public.salas
for select
to anon, authenticated
using (true);

drop policy if exists quizzes_select_public on public.quizzes;
create policy quizzes_select_public
on public.quizzes
for select
to anon, authenticated
using (true);

drop policy if exists quizzes_insert_public on public.quizzes;
create policy quizzes_insert_public
on public.quizzes
for insert
to anon, authenticated
with check (true);

drop policy if exists quizzes_update_public on public.quizzes;
create policy quizzes_update_public
on public.quizzes
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists ganadores_select_public on public."Ganadores";
create policy ganadores_select_public
on public."Ganadores"
for select
to anon, authenticated
using (true);

drop policy if exists ganadores_insert_public on public."Ganadores";
create policy ganadores_insert_public
on public."Ganadores"
for insert
to anon, authenticated
with check (true);

drop policy if exists ganadores_update_public on public."Ganadores";
create policy ganadores_update_public
on public."Ganadores"
for update
to anon, authenticated
using (true)
with check (true);
